/* calendarworkinghours.sql
DML to create workingHours testdata.
@creator dgr
@history	2015-04-03	dgr	create
*/

INSERT INTO calendarWorkingHours (calendarId, workingHoursId, weekDayKey) VALUES 
((select calendarId from calendar where title = 'pta1234'), (select workingHoursId from workingHours where morningFrom = '09:00:00'), 'MON'),
((select calendarId from calendar where title = 'pta1234'), (select workingHoursId from workingHours where afternoonFrom = '15:00:00'), 'TUE'),
((select calendarId from calendar where title = 'pta1234'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'WED'),
((select calendarId from calendar where title = 'pta1234'), (select workingHoursId from workingHours where afternoonFrom = '14:00:00'), 'THU'),
((select calendarId from calendar where title = 'pta1234'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'THU'),
((select calendarId from calendar where title = 'pta1234'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SAT'),
((select calendarId from calendar where title = 'pta1234'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SUN'),
((select calendarId from calendar where title = 'dru8472'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'MON'),
((select calendarId from calendar where title = 'dru8472'), (select workingHoursId from workingHours where afternoonFrom = '15:00:00'), 'TUE'),
((select calendarId from calendar where title = 'dru8472'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'WED'),
((select calendarId from calendar where title = 'dru8472'), (select workingHoursId from workingHours where afternoonFrom = '14:00:00'), 'THU'),
((select calendarId from calendar where title = 'dru8472'), (select workingHoursId from workingHours where afternoonFrom = '14:00:00'), 'FRI'),
((select calendarId from calendar where title = 'dru8472'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SAT'),
((select calendarId from calendar where title = 'dru8472'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SUN'),
((select calendarId from calendar where title = 'abc1234'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'MON'),
((select calendarId from calendar where title = 'abc1234'), (select workingHoursId from workingHours where afternoonFrom = '15:00:00'), 'TUE'),
((select calendarId from calendar where title = 'abc1234'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'WED'),
((select calendarId from calendar where title = 'abc1234'), (select workingHoursId from workingHours where afternoonFrom = '14:00:00'), 'THU'),
((select calendarId from calendar where title = 'abc1234'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'THU'),
((select calendarId from calendar where title = 'abc1234'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SAT'),
((select calendarId from calendar where title = 'abc1234'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SUN'),
((select calendarId from calendar where title = 'xyz7890'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'MON'),
((select calendarId from calendar where title = 'xyz7890'), (select workingHoursId from workingHours where afternoonFrom = '15:00:00'), 'TUE'),
((select calendarId from calendar where title = 'xyz7890'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'WED'),
((select calendarId from calendar where title = 'xyz7890'), (select workingHoursId from workingHours where morningFrom = '10:00:00'), 'THU'),
((select calendarId from calendar where title = 'xyz7890'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'THU'),
((select calendarId from calendar where title = 'xyz7890'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SAT'),
((select calendarId from calendar where title = 'xyz7890'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SUN'),
((select calendarId from calendar where title = 'ort1234'), (select workingHoursId from workingHours where morningFrom = '09:00:00'), 'MON'),
((select calendarId from calendar where title = 'ort1234'), (select workingHoursId from workingHours where afternoonFrom = '15:00:00'), 'TUE'),
((select calendarId from calendar where title = 'ort1234'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'WED'),
((select calendarId from calendar where title = 'ort1234'), (select workingHoursId from workingHours where afternoonFrom = '14:00:00'), 'THU'),
((select calendarId from calendar where title = 'ort1234'), (select workingHoursId from workingHours where afternoonFrom = '14:00:00'), 'FRI'),
((select calendarId from calendar where title = 'ort1234'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SAT'),
((select calendarId from calendar where title = 'ort1234'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SUN'),
((select calendarId from calendar where title = 'ort5678'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'MON'),
((select calendarId from calendar where title = 'ort5678'), (select workingHoursId from workingHours where afternoonFrom = '15:00:00'), 'TUE'),
((select calendarId from calendar where title = 'ort5678'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'WED'),
((select calendarId from calendar where title = 'ort5678'), (select workingHoursId from workingHours where morningFrom = '10:00:00'), 'THU'),
((select calendarId from calendar where title = 'ort5678'), (select workingHoursId from workingHours where morningFrom = '08:00:00'), 'THU'),
((select calendarId from calendar where title = 'ort5678'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SAT'),
((select calendarId from calendar where title = 'ort5678'), (select workingHoursId from workingHours where morningFrom is null and afternoonFrom is null), 'SUN');