/* medicine.sql
DDL to create medicine table.
@creator dgr
@history	2015-03-28	dgr	create https://www.mockaroo.com/a8c1aa60
*/

insert into medicine (medicineId, diagnosisId, name, dose) values 
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 45), 'Sodium Fluoride', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 29), 'MEPIVACAINE HYDROCHLORIDE', '3x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 23), 'Spinach', null),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 39), 'DEXTROMETHORPHAN HYDROBROMIDE', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 57), 'TRIBASIC CALCIUM PHOSPHATE', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 23), 'Furosemide', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 48), 'Insects (whole body) cockroach mix', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 68), 'Furosemide', '3x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 48), 'AVOBENZONE, HOMOSALATE, OCTOCRYLENE, OXYBENZONE', '3x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 31), 'mometasone furoate', null),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 19), 'Aurum Hypericum Stibium Special Order', '2x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 97), 'triazolam', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 26), 'OXYGEN', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 26), 'Zinc Oxide 11.6%, Titanium Dioxide 0.67%', '2x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 97), 'Fexofenadine HCl', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 26), 'Carvedilol', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 59), 'Acetaminophen, Diphenhydramine HCl', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 36), 'Echinacea,Baptisia tinctoria, Hydrastis canadensis, Myrrha, Nasturtium aquaticum, Phytolacca decandra, Trigonella foenum-graecum, Zone 9 Tree, Zone 9 Weed, Zone 9 Grass', '2x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 49), 'LORAZEPAM', '2x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 57), 'thrombin, topical (bovine)', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 3), 'SODIUM FLUORIDE', '3x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 86), 'Bacitracin', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 90), 'TITANIUM DIOXIDE, ZINC OXIDE', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 49), 'Avobenzone, Homosalate, Octisalate, Octocrylene, Oxybenzone', '2x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 97), 'Witch Hazel', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 53), 'Melaleuca Pollen', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 6), 'bismuth subsalicylate', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 1), 'Cocklebur', '2x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 92), 'Vitamin C, Calcium, Iron, Vitamin D3, Vitamin E, Thiamin, Riboflavin, Niacinamide, Vitamin B6, Folic Acid, Iodine, Zinc, Copper, Docusate Sodium', '2x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 86), 'Clarithromycin', '3x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 71), 'fluticasone propionate and salmeterol', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 59), 'Leucine, Phenylalanine, Lysine, Methionine, Isoleucine, Valine, Histidine, Threonine, Tryptophan, Alanine, Glycine, Arginine, Proline, Serine, Tyrosine, Sodium Acetate, Dibasic Potassium Phosphate, Ma', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 28), 'Guaifenesin', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 28), 'Olanzapine', '3x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 89), 'Octinoxate and Oxybenzone', '2x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 44), 'perphenazine', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 5), 'Dicyclomine Hydrochloride', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 54), 'Gabapentin', '2x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 75), 'TITANIUM DIOXIDE, OCTINOXATE, ZINC OXIDE', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 24), 'Zinc Oxide 7%', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 37), 'Agaricus 30c, Belladonna 30c, Hyoscyamus 30c, Kali Brom 30c, Natrum Mur 30c, Nux Vomica 30c', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 74), 'Lisinopril', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 66), 'SULFUR', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 35), 'MIDAZOLAM HYDROCHLORIDE', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 98), 'CAPTORPIL', '3x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 70), 'ZINC OXIDE', '3x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 12), 'Brompheniramine Maleate, Pseudoephedrine Hydrochloride, and Dextromethorphan Hydrobromide', '3x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 75), 'Quetiapine Fumarate', null),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 47), 'ALCOHOL', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 79), 'Curly Dock', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 52), 'ASPIRIN', '2x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 90), 'Clematis Recta Flowering Top, Arsenic Triiodide, Sodium Borate, Oyster Shell Calcium Carbonate, Crude, Graphite, Daphne Mezereum Bark, Proteus Morganii, Sodium Chloride, Phytolacca Americana Root, Sepia Officinalis Juice, Sulfur, Thyroid', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 58), 'BENZALKONIUM CHLORIDE', '1x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 74), 'USTILAGO MAYDIS', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 13), 'bismuth subsalicylate', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 16), 'Oxygen', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 93), 'Acetaminophen, dextromethorphan hydrobromide, guaifenesin, and phenylephrine hydrochloride', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 61), 'Ammonium Carbonicum, Apis Mellifica, Argentum Metallicum, Arsenicum Album, Dulcamara, Mezereum', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 7), 'Hydrocortisone Acetate', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 31), 'montelukast sodium', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 77), 'Alkyl (68% C12, 32% C14) Dimethyl Ethylbenzyl Ammonium Chloride and Alkyl Dimethyl Benzyl Ammonium Chloride', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 25), 'not applicable', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 19), 'PANTHENOL', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 50), 'ropinirole hydrochloride', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 61), 'NORTRIPTYLINE HYDROCHLORIDE', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 33), 'Lisinopril', '2x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 83), 'Aconitum napellus, Apis mellifica, Arnica montana, Cartilago suis, Hydrastis canadensis, Hypericum perforatum, Rhus toxicodendron, Thuja occidentalis,', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 53), 'Phenazopyridine Hydrochloride', '3x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 35), 'POTASSIUM CHLORIDE', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 19), 'Titanium Dioxide', '2x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 3), 'Broccoli', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 7), 'MENTHOL', '3x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 13), 'Avobenzone, Octisalate, Octocrylene, and Oxybenzone', '3x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 8), 'simethicone', '3x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 39), 'POTASSIUM ACETATE', '3x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 92), 'Benzalkonium Chloride', '1x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 88), 'Benzalkonium Chloride', null),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 84), 'Escitalopram', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 76), 'Ondansetron', '2x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 29), 'Eupatorium Perfoliatum, Arnica Montana, Benzoicum Acidum, Echinacea, Mercurialis Perennis, Apis Mellifica, Baptisia Tinctoria', '3x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 20), 'Bismuth subsalicylate', null),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 38), 'gemcitabine hydrochloride', '2x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 56), 'MENTHOL', '2x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 82), 'ROPINIROLE HYDROCHLORIDE', '1x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 31), 'Cherry plum,', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 20), 'OCTINOXATE', '1x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 15), 'Gabapentin', '2x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 94), 'Hydrochlorothiazide', '1x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 90), 'furosemide', '2x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 39), 'Avobenzone, Homosalate, Octisalate, Octocrylene and Oxybenzone', '2x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 69), 'LIDOCAINE HYDROCHLORIDE ANHYDROUS', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 36), 'White Mulberry', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 76), 'neomycin sulfate, polymyxin b sulfate and hydrocortisone', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 62), 'Butalbital, Acetaminophen and Caffeine', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 85), 'Guaifenesin and Codeine Phosphate', '1x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 57), 'Pyrithione Zinc', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 68), 'DIMETHICONE', '2x3'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 28), 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', '3x1'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 22), 'ibuprofen', '1x2'),
(null, (select diagnosisId from (SELECT @rownum := @rownum + 1 ROWNUM , diagnosis.* FROM (SELECT @rownum := 0) r, diagnosis) t where rownum = 15), 'venlafaxine hydrochloride', '3x3');
